# Generated by Django 5.2.16 on 2026-08-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordentry',
            old_name='password',
            new_name='encrypted_password',
        ),
    ]
