# Generated by Django 5.2.16 on 2026-08-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordentry',
            old_name='encrypted_password',
            new_name='password',
        ),
    ]
